name: Release Charts

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write
  actions: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Helm lint
        run: helm lint enva-umbrella

      - name: Set git config for chart-releaser push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: .
          config: cr.yaml
          skip_existing: true
          mark_as_latest: true
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Pages deploy
        run: gh workflow run "Deploy to GitHub Pages" --ref gh-pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
